// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eogjskunjowwjkqjpbhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZ2pza3Vuam93d2prcWpwYmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjgzOTIsImV4cCI6MjA3MzM0NDM5Mn0.FrxpDAKuFYSyl_PTxw-59jxzhzwSBy57lfoskIlmU78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});